# Generated by Django 3.1.4 on 2020-12-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortURL",
            fields=[
                ("main_url", models.URLField(db_index=True)),
                ("short_id", models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
    ]
