# Generated by Django 3.1.4 on 2020-12-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("url_shortener", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TraceOperation",
            fields=[
                ("view_path", models.CharField(max_length=200, primary_key=True, serialize=False)),
                ("hit_count", models.IntegerField(default=1)),
            ],
        ),
    ]
